[package]
name = "dumb_http_parser"
version = "0.1.2"
authors = ["hrishi <hrishikesh.mk1@gmail.com>"]
description = "Parse HTTP request"
license = "MIT"
repository= "https://github.com/hrishimk/dumb_http_parser"

[dependencies]
url="1.7.2"
